[package]
name = "textual"
version = "0.0.0"
description = "Plain and restricted text I/O and strings"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["stream", "text"]
categories = ["os", "text-processing"]
repository = "https://github.com/sunfishcode/textual"
edition = "2018"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.2"

[dependencies]
interactive-streams = { git = "https://github.com/sunfishcode/interactive-streams", branch = "main" }
io-ext = { git = "https://github.com/sunfishcode/io-ext", branch = "main" }
io-ext-adapters = { git = "https://github.com/sunfishcode/io-ext-adapters", branch = "main" }
unicode-normalization = { git = "https://github.com/sunfishcode/unicode-normalization", branch = "flush-nfc-after-nl-and-cgj" }
terminal-support = { git = "https://github.com/sunfishcode/terminal-support", branch = "main", optional = true }

[dev-dependencies]
anyhow = "1.0.37"

[badges]
maintenance = { status = "actively-developed" }
