[package]
name = "text-streams"
version = "0.0.0"
description = "Library for working with text streams"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["stream", "text"]
categories = ["os", "text-processing"]
repository = "https://github.com/sunfishcode/text-streams"
edition = "2018"
readme = "README.md"

[dependencies]
io-ext = { path = "../io-ext" }
io-ext-adapters = { path = "../io-ext-adapters" }
unicode-normalization = { path = "../unicode-normalization" }

[dev-dependencies]
anyhow = "1.0.35"

[features]
default = []
nightly = ["io-ext/nightly", "io-ext-adapters/nightly"]

[badges]
maintenance = { status = "actively-developed" }
