[package]
name = "text-str"
version = "0.0.0"
description = "Basic Text strings and I/O streams"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["stream", "text"]
categories = ["os", "text-processing"]
repository = "https://github.com/sunfishcode/text-str"
edition = "2018"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.2"

[dependencies]
duplex = "0.1.0"
layered-io = "0.2.0"
unicode-normalization = { git = "https://github.com/sunfishcode/unicode-normalization", branch = "flush-nfc-after-nl-and-cgj" }
terminal-io = { version = "0.1.0", optional = true }

[target.'cfg(windows)'.dependencies]
unsafe-io = "0.3.0"

[dev-dependencies]
anyhow = "1.0.37"

[badges]
maintenance = { status = "actively-developed" }
