[package]
name = "basic-text"
version = "0.2.1-alpha.0"
description = "Basic Text strings and I/O streams"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["stream", "text"]
categories = ["os", "text-processing"]
repository = "https://github.com/sunfishcode/basic-text"
edition = "2018"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.3"

[dependencies]
duplex = "0.2.0"
layered-io = "0.3.1"
unicode-normalization = "0.1.17"
terminal-io = { version = "0.2.1", optional = true }
unsafe-io = "0.5.2"
utf8-io = { version = "0.3.1", features = ["layered-io"] }

[dev-dependencies]
anyhow = "1.0.37"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = ["restricted-text"]
